### ISSUE TITLE
live site: tsl certificate expired

### ISSUE THREAD

**Issue by orochi02** [notarizer/notarizer#7] opened 2021-11-30 09:33 UTC
image:
![grafik](https://user-images.githubusercontent.com/37455935/144021669-159a721b-b518-40d6-bb84-c9019c965d99.png)
its in german but should be quite self explanatory

**Comment by kemp** [comment] 2021-12-01 00:28
Thank you so much for this report!

The issue is now fixed.

**Closed by kemp** 2021-12-01 00:28 UTC
